###################
# Hyprland Config #
###################

source = ~/.config/hypr/conf/monitor.conf
source = ~/.config/hypr/conf/keywords.conf
source = ~/.config/hypr/conf/autostart.conf
source = ~/.config/hypr/conf/env.conf
source = ~/.config/hypr/conf/look-and-feel.conf
source = ~/.config/hypr/conf/input.conf
source = ~/.config/hypr/conf/window-rules.conf

# All Keybindings
source = ~/.config/hypr/conf/keybindings.conf
source = ~/.config/hypr/conf/app-keybindings.conf
