# Open Browser
bind = $mainMod, B, exec, hyprctl dispatch exec firefox

# Hyprlock Keybinding
bind = $mainMod, X, exec, hyprlock

# Reload Waybar
bind = $mainMod, R, exec, pkill waybar && hyprctl dispatch exec waybar

# Reload Hyprpaper
bind = $mainMod SHIFT, W, exec, pkill hyprpaper && hyprctl dispatch exec hyprpaper

# Change to Random wallpaper
bind = $mainMod, W, exec, ~/.config/hypr/scripts/wallpaper-change.sh

# Open calculator
bind = $mainMod, C, exec, hyprctl dispatch exec gnome-calculator

# Open volume control
bind = $mainMod, V, exec, hyprctl dispatch exec pavucontrol

# Screenshot
$screenshotarea = hyprctl keyword animation "fadeOut,0,0,default"; grimblast --notify copysave area; hyprctl keyword animation "fadeOut,1,4,default"
bind = $mainMod SHIFT, T, exec, $screenshotarea
bind = , Print, exec, grimblast --notify --cursor copysave output
bind = ALT, Print, exec, grimblast --notify --cursor copysave screen

# Notification tray
bind = $mainMod, N, exec, swaync-client -t

# Hyprpicker: a color picker
bind = $mainMod SHIFT, X, exec, hyprpicker -a -n

