exec-once = systemctl --user import-environment 
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = /usr/lib/mate-polkit/polkit-mate-authentication-agent-1
exec-once = waybar & swaync &
exec-once = nm-applet & copyq &
exec-once = blueman-applet &
exec-once = hyprpaper & hypridle &
exec-once = wl-clipboard-history -t
exec-once = gnome-keyring-daemon --start --components=secrets
exec-once = ~/.config/hypr/xdg-desktop-portal
