################
### MONITORS ###
################

# See https://wiki.hyprland.org/Configuring/Monitors/
# monitor=eDP-1,disable
monitor=,preferred,auto,1

# Hyprlock on lid close
bindl=,switch:Lid Switch, exec, hyprlock
